export const categories = [
  { id: "mba", name: "MBA", short: "Master of Business Admin", description: "Leadership, strategy, and management for future CEOs.", universities: 84, icon: "briefcase", accent: "268" },
  { id: "mca", name: "MCA", short: "Master of Computer Apps", description: "Advanced software engineering & computing careers.", universities: 62, icon: "code", accent: "200" },
  { id: "btech", name: "B.Tech", short: "Bachelor of Technology", description: "Engineer tomorrow with core & emerging tech tracks.", universities: 96, icon: "cpu", accent: "275" },
  { id: "bba", name: "BBA", short: "Bachelor of Business Admin", description: "Foundations of business, marketing and finance.", universities: 71, icon: "trending-up", accent: "82" },
  { id: "bca", name: "BCA", short: "Bachelor of Computer Apps", description: "Programming, systems, and app development.", universities: 58, icon: "monitor", accent: "145" },
  { id: "ds", name: "Data Science", short: "Data & Analytics", description: "Turn raw data into decisions with modern ML.", universities: 42, icon: "bar-chart-3", accent: "320" },
  { id: "llb", name: "LLB", short: "Bachelor of Law", description: "Constitutional, corporate & criminal law programs.", universities: 39, icon: "scale", accent: "55" },
  { id: "med", name: "M.Ed", short: "Master of Education", description: "Educator pathways with pedagogy & leadership.", universities: 34, icon: "graduation-cap", accent: "260" },
];

export const programTypes = [
  "Bachelor's",
  "Master's",
  "Executive",
  "Certification",
  "Diploma",
  "Doctorate",
];

export const trendingChips = [
  "MBA", "MCA", "BCA", "BBA", "B.Tech", "M.Tech", "LLB", "B.Com",
  "Data Science", "AI", "Cloud Computing", "Cyber Security",
];

export const featuredUniversities = [
  {
    id: "amity",
    name: "Amity University Online",
    short: "AUO",
    logoColor: "0.55 0.22 268",
    bannerFrom: "0.42 0.19 268",
    bannerTo: "0.62 0.22 275",
    rating: 4.7,
    reviews: 12480,
    naac: "A+",
    ugc: true,
    nirf: 32,
    feeMin: 45000,
    feeMax: 220000,
    duration: "2 Years",
    mode: "Online",
    description: "UGC-entitled online degrees across management, tech and law with global faculty.",
    location: "Noida, India",
  },
  {
    id: "manipal",
    name: "Manipal University Jaipur",
    short: "MUJ",
    logoColor: "0.6 0.18 55",
    bannerFrom: "0.5 0.18 45",
    bannerTo: "0.72 0.16 82",
    rating: 4.8,
    reviews: 18320,
    naac: "A+",
    ugc: true,
    nirf: 24,
    feeMin: 62000,
    feeMax: 280000,
    duration: "3–4 Years",
    mode: "Online / Hybrid",
    description: "Legacy of Manipal — premium online MBA, MCA and B.Tech pathways.",
    location: "Jaipur, India",
  },
  {
    id: "jain",
    name: "Jain (Deemed-to-be) University",
    short: "JAIN",
    logoColor: "0.55 0.2 145",
    bannerFrom: "0.42 0.16 160",
    bannerTo: "0.65 0.18 145",
    rating: 4.6,
    reviews: 9640,
    naac: "A++",
    ugc: true,
    nirf: 68,
    feeMin: 40000,
    feeMax: 190000,
    duration: "2–3 Years",
    mode: "Online",
    description: "Industry-aligned online programs with strong placement support.",
    location: "Bangalore, India",
  },
  {
    id: "lpu",
    name: "Lovely Professional University",
    short: "LPU",
    logoColor: "0.6 0.22 25",
    bannerFrom: "0.5 0.2 20",
    bannerTo: "0.7 0.2 40",
    rating: 4.5,
    reviews: 15120,
    naac: "A+",
    ugc: true,
    nirf: 27,
    feeMin: 55000,
    feeMax: 260000,
    duration: "2–4 Years",
    mode: "Online / Distance",
    description: "One of India's largest universities with rich program diversity.",
    location: "Punjab, India",
  },
  {
    id: "chandigarh",
    name: "Chandigarh University Online",
    short: "CU",
    logoColor: "0.6 0.2 320",
    bannerFrom: "0.5 0.2 310",
    bannerTo: "0.7 0.2 335",
    rating: 4.6,
    reviews: 11200,
    naac: "A+",
    ugc: true,
    nirf: 41,
    feeMin: 48000,
    feeMax: 240000,
    duration: "2–3 Years",
    mode: "Online",
    description: "Modern online campus with immersive learning and career labs.",
    location: "Chandigarh, India",
  },
  {
    id: "symbiosis",
    name: "Symbiosis Centre for Distance Learning",
    short: "SCDL",
    logoColor: "0.55 0.16 200",
    bannerFrom: "0.42 0.14 210",
    bannerTo: "0.68 0.15 195",
    rating: 4.7,
    reviews: 20450,
    naac: "A",
    ugc: true,
    nirf: null,
    feeMin: 42000,
    feeMax: 180000,
    duration: "1–2 Years",
    mode: "Distance / Online",
    description: "Trusted PG diplomas and postgrad programs from the Symbiosis family.",
    location: "Pune, India",
  },
];

export const searchGroups = {
  recent: ["MBA in Finance", "Manipal Online B.Tech", "Data Science PG"],
  trending: ["Online MBA 2026", "AI & ML Specialization", "Executive MBA"],
  universities: ["Amity University", "Manipal University", "Chandigarh University", "LPU Online"],
  degrees: ["MBA", "MCA", "B.Tech", "BBA", "Data Science", "LLB"],
};